### ISSUE TITLE
Serialize DynamicObject containing both 'double' and 'decimal' properties with Json.NET

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#1]
Hello,

We seem to have stuck at the problem serializing/deserializing DynamicObject's with properties of types 'double' and 'decimal' in the same object (or graph) using Json.NET serializer. The easiest way to reproduce the problem for you would be to change the datatype 'double' to 'decimal' in [this field](https://github.com/6bee/aqua-core/blob/master/src/Aqua/Aqua.Tests/Serialization/Dynamic/DynamicObject/When_using_dynamic_object_for_complex_object_tree.cs#L12) and rerun the tests.

```
Test Name:  Aqua.Tests.Serialization.Dynamic.DynamicObject.When_using_dynamic_object_for_complex_object_tree.Clone_should_contain_simple_decimal_property
Test FullName:  Aqua.Tests.Serialization.Dynamic.DynamicObject.When_using_dynamic_object_for_complex_object_tree.Clone_should_contain_simple_decimal_property
Test Source:    \aqua-core\src\Aqua\Aqua.Tests\Serialization\Dynamic\DynamicObject\When_using_dynamic_object_for_complex_object_tree.cs : line 43
Test Outcome:   Failed
Test Duration:  0:00:00,014

Result StackTrace:  at Aqua.Tests.Serialization.Dynamic.DynamicObject.When_using_dynamic_object_for_complex_object_tree.Clone_should_contain_simple_decimal_property() in \aqua-core\src\Aqua\Aqua.Tests\Serialization\Dynamic\DynamicObject\When_using_dynamic_object_for_complex_object_tree.cs:line 44
Result Message: 
Assert.Equal() Failure
Expected: 123 (System.Decimal)
Actual:   123 (System.Double)
```

One may configure Json.NET to parse numeric literals as either 'double' or 'decimal' using [FloatParseHandling](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_FloatParseHandling.htm) option, but there is no option to preserve the original CLR type. That means DynamicObject must somehow supply it explicitly.

How would you recommend us to proceed? Thank you in advance!

**Comment by 6bee** [comment]
One easy way might be to simply map primitive types to string using DynamicObjectMapper:

`var mapper = new DynamicObjectMapper(formatPrimitiveTypesAsString: true);`

A second option is to subclass `DynamicObjectMapper`and override `MapFromDynamicObjectGraph` and `MapToDynamicObjectGraph`methods to deal with mapping/formatting/wrapping double and decimal values while converting your object graph into a dynamic object structure and back. Like in this [sample](https://github.com/6bee/aqua-core/blob/master/test/Aqua.Tests/Dynamic/DynamicObjectMapper/CustomMapper/When_mapping_int_as_string_and_long_as_long.cs#L37).

**Comment by azabluda** [comment]
`formatPrimitiveTypesAsString` worked just fine! Thank you.
