### ISSUE TITLE
Typo in DynamicObjectMapper.ParseToNativeType

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#12]
There seems to be a question mark `?` missing after the second `short`
```c#
if (targetType == typeof(short) || targetType == typeof(short))
{
    return short.Parse(value);
}
```
This causes _System.NotImplementedException: string parser for type System.Nullable`1[System.Int16] is not implemented_.

**Comment by 6bee** [comment]
Yes, indeed. Changed it to `short?`.
