### ISSUE TITLE
Mapping of Nullable<Enum>

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#13]
If I change the type of `EnumProperty` in `Aqua.Tests.Dynamic.DynamicObject.When_converting_to_object_with_enum.ClassWithEnum` to `CustomEnum?` then the tests would no longer pass. There seems to be a problem with enum values stored as `string` and `int`.

**Comment by 6bee** [comment]
should be resolved in version `4.0.0-alpha-055`

**Comment by azabluda** [comment]
This one works fine now, but enums still deserve certain attention. I created another issue https://github.com/6bee/Remote.Linq/issues/17.
