### ISSUE TITLE
netstandard1.6 version of aqua-core is not fully compatible with its netstandard1.3 counterpart

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#14]
I have a library referencing aqua-core and targeting netstandard1.3. It contains the following line of code
```c#
... = new TypeResolver(); // resolves into new TypeResolver(null, false)
```
The library compiles just fine, but its consuming application (in my case netcoreapp1.0 xunit test project) seems to be pulling the netstandard1.6 version of aqua-core. It doesn't look too wrong to me and I actually don't mind if it happens, but apparently aqua-core/ns1.6 does no longer expose the 2-arg ctor of class `TypeResolver` which leads to a runtime error
```
System.MissingMethodException : Method not found: 'Void Aqua.TypeSystem.TypeResolver..ctor(System.Func`2<Aqua.TypeSystem.TypeInfo,System.Type>, Boolean)'.
```

After some more reflection I tend to see here a contradiction with the general statement of Microsoft
> .NET Standard versions are backward compatible. That means that netstandard1.0 libraries run on netstandard1.1 platforms and higher, and so on...

If we apply this statement not only to .NET Standard itself but also to _libraries targeting netstandardX_Y_ then it explains my `MissingMethodException`.

Can you bring the following signature to aqua-core/ns1.6 for compatibility with aqua-core/ns1.3?
```c#
public TypeResolver(Func<TypeInfo, Type> typeEmitter, bool validateIncludingPropertyInfos)
```
or do you have any better ideas/suggestions?

**Comment by 6bee** [comment]
Valid point!

I've added an overload of the `ctor` in `netstandard1.6` compatible with the one in `netstandard1.3` available in `aqua-core 4.0.0-alpha-058`


Out of curiosity: would you happen to know if there’s a way to fixate the target version of a library to prevent pulling `netstandard1.6` instead of `netstandard1.3`? 
My unit tests for the netstandard libraries are implemented in a `netcoreapp1.0`. Thesting the multitargeting dll always pulls `netstandard1.6` version only.

**Comment by azabluda** [comment]
Thanks for the quick fix!

No, unfortunately I don't know how to force `netcoreapp1.0` to use a lower version of `netstandard` library if the higher one is available. One can of course always create separate projects for 1.3 and 1.6 an reference them explicitly, but its painful and no fun at all.

On the other hand Microsoft would probably consider this case rare (and hence poorly support it), because normally a developer would want to implement a library targeting the lowest possible version of `netstandard` which will automatically work on all higher platforms. Why do you have a special version for 1.6? Is 1.3 not sufficiently good?

**Comment by 6bee** [comment]
Thanks for your feedback.

There's good reason to target both version for the very case of `TypeResolver`. 
While in `netstandard1.6` `DependencyContext.Default.RuntimeLibraries`may be utilized to iterate loaded assemblies and types, this type is not available in `netstandard1.3` where we need to engage the file system as a primitive workaround instead.

netstandard1.3
https://github.com/6bee/aqua-core/blob/master/src/Aqua/TypeSystem/TypeResolver.NETSTANDARD1_3.cs#L19-L26

netstandard1.6
https://github.com/6bee/aqua-core/blob/master/src/Aqua/TypeSystem/TypeResolver.NETSTANDARD.cs#L17-L22

**Comment by azabluda** [comment]
I see... Dealing with loaded assemblies is never a pleasure, and it's getting especially frustrating in `netstandard`. But still I'm not fully convinced that we necessarily need different constructor signatures here.

As I understand the whole story boils down to a "_give me `System.Type` by its full name_" problem, which I would simply extract into a virtual method of `TypeResolver` with three different default implementations (for 1.3, 1.6 and full .net). If somebody isn't quite happy with the standard implementation, then they may just subclass+override (possibly in a way which has nothing to do with iterating `IEnumerable<RuntimeLibrary>`). That would feel more natural and flexible to me, and (returning to our topic) would not affect the constructor signature.

But anyway this is a separate discussion. The current issue can be closed.

**Comment by 6bee** [comment]
Good suggestion, thanks! I've consolidated the constructor and provided an platform specific default implementation of `GetAssemblies()` which may be overridden in a subclass.
