### ISSUE TITLE
Attaching an entity of type 'my sub-entity type' failed because another entity of the same type already has the same primary key value.

### ISSUE THREAD

**Issue by sdmckenna9** [6bee/aqua-core#20]
Good morning,
  First off, thanks so much for creating this aqua-core package. It has enabled me to pass entire graphs of data returned by Entity Framework from a WCF Service successfully to the client!
  I'm working on the part of our application that makes changes to the graph of data and returns it to the WCF Service to handle the updates. I convert the updated graph object back to DynamicObject and pass it as a parameter to my WCF Service method UpdateXYZ. The service is successfully receiving the DynamicObject as a parameter, and successfully converting it back to an object graph of my type in the first line below. However, I am receiving the error above when the second line runs to attach the entity to the service's context. It isn't the top-level MyType that it's failing on, but rather one of the nested types in the graph.
  Am I going about this correctly? I don't want to have to perform a field-by-field copy of the received data onto a newly retrieved entity from my service's DbContext.

            MyType app = new DynamicObjectMapper().Map(obj) as MyType;
            context.MyTypeCollection.Attach(app);
            context.SaveChanges();

Edit: If I originally query the data as "AsNoTracking", this Attach error on the return trip goes away, but I have to manually set the EF record state to Modified (code below) to get it to save the changes. However, without the change tracking enabled while work is being done on the client side, I'll have no idea which nested entities in the graph were added, modified, or possibly deleted, so this doesn't really fix my issue.
            context.Entry(app).State = EntityState.Modified;
 

Thanks!

**Comment by 6bee** [comment]
Yes I know, change tracking and properly appyling changes back to a datacontext for persisting changes is not trivial. Unless I get you wrong, this is unrelated to serialization though (i.e. aqua-core in this case) and I would encourage you to seek support on EF/EF Core.

**Comment by sdmckenna9** [comment]
Fair enough. I was able to resolve this by using the AsNoTracking in combination with rolling my own tracking mechanism into the entities passed to the client (see generic class below). I use a switch statement to loop through all the nested entities and check the RecordState of each one to see what work needs to be done against the DbContext (Attach & Modify, Add, or Remove).
Thanks once again!

    [Serializable]
    public class ChangeTrackingWrapper<T>   // T is the Entity Type 
    {
        public T Entity { get; set; }
        public RecordStateEnum RecordState { get; set; }

        public ChangeTrackingWrapper(T entity, RecordStateEnum state)
        {
            this.Entity = entity;
            this.RecordState = state;
        }
    }

    public enum RecordStateEnum
    {
        Unchanged = 0,
        Modified,
        Added,
        Deleted
    }
