### ISSUE TITLE
Test validating error message fails in non-english environment

### ISSUE THREAD

**Issue by L1tR05** [6bee/aqua-core#23]
In this test: test/Aqua.Tests/Dynamic/DynamicObjectMapper/When_mapping_dynamic_object_to_type_with_different_property_types
.cs

When the system environment is set to a non-english language, the exception messages are in a foreign language.

**Comment by 6bee** [comment]
@L1tR05 
Thank you very much for your work.
6bee/aqua-core/pull/24
