### ISSUE TITLE
[Question] Ability to recycle type cache at runtime

### ISSUE THREAD

**Issue by cosmintiru** [6bee/aqua-core#28]
Hello @6bee ,

First of all, thank you very much for the remote.linq and aqua-core libraries. It has allowed me to apply metaprogramming techniques. 

I'm currently playing around with the new AssemblyLoadContext from dotnet core 3.0, which allows me to dynamically compile ASTs and load the binary which plays quite nicely with remote.linq. 

The problem I'm facing now is that whenever I want to unload the context and recompile I fail to do that due to (I presume) the type cache which prevents GC to collect the assembly.

Before I go any deeper, given that you know the inner workings of this library the best, is a complete recycle of the emitted types feasible? Or a possible workaround as a hint?

The main outcome of this would be to be able to reuse remote.linq against the newly built types.

Thanks,
Cosmin

**Comment by 6bee** [comment]
Presuming you're referring to the `TypeResolver`'s type cache which is at instance level, you have the following options: 
- create and use your own implementation of `ITypeResolver`, or
- manage lifetime of `TypeResolver` by passing your own instance of this class to according methods (e.g. `Execute`-extension method)
- manage lifetime `ITypeResolver` of globally by setting the `TypeResolver.Instance`-property, which is used as a fallback wherever no explicit type resolver is specified.

Hope that helps?

**Comment by cosmintiru** [comment]
Will try it out. Thank you very much!

Just wanted to ask if there's a chance to get into other weird situations that makes everything futile.

**Comment by 6bee** [comment]
@cosmintiru 
After a second look I actually think it's not this cache causing the problem. Default `TypeResolver` (as well as `TypeEmitter`) implementation is using `TransparentCache<,>` for caching resolved (resp. emitted) types, which internally holds type as `WeakReference`s. As a consequence, GC should not be held up by these caches...
