### ISSUE TITLE
Culture mismatch: FormatNativeTypeAsString vs Serializers.

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#29]
After fca4dda1 FormatNativeTypeAsString uses InvariantCulture (which is good), yet the serializers still seem to be implicitly [using the CurrentCulture](https://github.com/6bee/aqua-core/blob/fca4dda1b72b5c89dfd2cfdab53499669d8ce317/src/Aqua.Newtonsoft.Json/NativeValueInspector.cs#L30). This causes a problem when the current culture defines a decimal separator different from the invariant one.
```cs
public abstract class When_serializing_dynamic_object
{
    // ...

    [Fact]
    public void Float_should_serialize()
    {
        CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("de");
        var result = Serialize<float, float>(0.1F, formatValuesAsStrings: true);
        result.ShouldBe(0.1F);
    }
}
```
Aqua.Tests.Serialization.Dynamic.DynamicObject.When_serializing_dynamic_object+JsonSerializer.Float_should_serialize [FAIL]
```
Shouldly.ShouldAssertException : result
    should be
0,1f
    but was
1E+08f
```

**Comment by 6bee** [comment]
Thank you so much for your valuable input, as always 👍 
Please checkout version `4.6.1`.

**Comment by azabluda** [comment]
You're always welcome @6bee and thanks a lot for another super fast fix!

I just noticed some room for improvement in the unit tests
1. Parameter `formatValuesAsStrings` is not used/propagated in https://github.com/6bee/aqua-core/blob/b8c78112f5ba64157810e1109c355d8b890e48fa/test/Aqua.Tests/Serialization/Dynamic/DynamicObject/When_serializing_dynamic_object.cs#L229
2. Changing the global `CultureInfo.CurrentCulture` may affect further tests running in the same runner process. I could recommend using the `IDisposable` technique similar to https://stackoverflow.com/a/5793154. With [C# 8.0](https://www.syncfusion.com/blogs/post/csharp-8-0-using-declaration.aspx) you don't even need  another nested scope anymore, so it will remain a one-liner.
```cs
public void Should_serialize_value(Type type, object value, CultureInfo cultureInfo)
{
    Skip.If(this.TestIs<JsonSerializer>() && type.Is<DateTimeOffset>(), "DateTimeOffset not supported by JsonSerializer");
    Skip.If(this.TestIs<JsonSerializer>() && type.Is<Complex>(), "Complex not supported by JsonSerializer");
    Skip.If(this.TestIs<JsonSerializer>() && type.Is<decimal>(), "Decimal not supported by JsonSerializer");

    using var cultureRunner = new CultureRunner(cultureInfo);
    // using var cultureRunner = cultureInfo.AsCurrent(); // <<< if you like it better

    var result = SerializeMethod.MakeGenericMethod(type).Invoke(this, new[] { value, true });
    result.ShouldBe(value, $"type: {type.FullName}");
}
```
