### ISSUE TITLE
ResolveMethod fails on explicit cast from decimal? to double? 

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#30]
```cs
[Fact]
public void ResolveMethod_ExplicitCast_should_return_original_method_info()
{
    var typeResolver = new TypeResolver();

    Expression<Func<decimal?, double?>> expr = x => (double?)x;
    System.Reflection.MethodInfo methodInfo = ((UnaryExpression)expr.Body).Method;
    Aqua.TypeSystem.MethodInfo mappedMethod = new Aqua.TypeSystem.MethodInfo(methodInfo);
    System.Reflection.MethodInfo resolvedMethod = mappedMethod.ResolveMethod(typeResolver);

    resolvedMethod.ShouldBe(methodInfo);
}
```
```
Shouldly.ShouldAssertException : resolvedMethod
    should be
Double op_Explicit(System.Decimal)
    but was
Byte op_Explicit(System.Decimal)
```

**Comment by 6bee** [comment]
Indeed, I forgot about cast operators and had to include _return type_ within `MethodInfo`. 
This should now work too.

**Comment by azabluda** [comment]
The fix looks good, thank you. Would it be possible to cherry-pick it into the 4.6.x release branch?

**Comment by 6bee** [comment]
Good point!
I'll create a release package as soon as you approve the debug build are working for you as needed. 
Please use `aqua-core.4.6.3-beta-001` and/or `Remote.Linq.6.2.2-beta-001` using myget package source: https://www.myget.org/F/aqua/api/v3/index.json

**Comment by azabluda** [comment]
Works fine. Feel free to release the packages.

**Comment by 6bee** [comment]
Released `aqua-core.4.6.3` and `Remote.Linq.6.2.2`

**Comment by azabluda** [comment]
`Remote.Linq.6.2.2` still underway?

**Comment by 6bee** [comment]
My fault, sorry. The packages are ready now.
