### ISSUE TITLE
When_resolving_hidden_property.ResolveMemberInfo_should_return_original_property_info

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#32]
Version 4.6.3.

The following test fails with `System.Reflection.AmbiguousMatchException`

```cs
[Fact]
public void ResolveMemberInfo_should_return_original_property_info()
{
    var typeResolver = new TypeResolver();

    System.Reflection.TypeInfo type = typeof(TypeHiding).GetTypeInfo();
    System.Reflection.PropertyInfo propertyInfo = type.GetDeclaredProperty(nameof(TypeHiding.Property));
    Aqua.TypeSystem.PropertyInfo mappedProperty = new Aqua.TypeSystem.PropertyInfo(propertyInfo);
    System.Reflection.MemberInfo resolvedMemberInfo = mappedProperty.ResolveMemberInfo(typeResolver);

    resolvedMemberInfo.ShouldBe(propertyInfo);
}
```

Related to
* https://github.com/6bee/aqua-core/commit/a595e67e5bd8244870461c383fc73a70604d00ef#diff-48436613902563baf24744a8a84a1f71R89
* #27

**Comment by 6bee** [comment]
This was solved for `5.0` but not for `4.6.x` yet. I'm going to release a patch for this.
Would you need a patch for `Remote.Linq` with updated dependency version too?

**Comment by azabluda** [comment]
For now I'm just going to reference a specific version of AC, so there's no need for a separate release of RL. Thanks!

**Comment by 6bee** [comment]
Version `4.6.4` has released containing the fix for this issue.
