### ISSUE TITLE
How to import and gen from Excel

### ISSUE THREAD

**Issue by fasteddys** [6bee/aqua-core#38]
Hello this a nice place to keep the meta data of my projects. I used to have an excel spreadsheet with the table names & two Cols for the name and type, I would like to import that into your project - so I can generate the model objects from from here.

```
Excel Col - ClassName 
Excel Col - AtrributeName
Excel Col - Type
```

How can I template this excel sheet to a simple C# POCO model class with the name and type

**Comment by 6bee** [comment]
I'm not quite sure I understand your scenario?

Typically your POCO-type would declare the spreadsheet colums as properties.
```C#
// POCO type
public record Record
{
  public string Name { get; init; }
  public string Type { get; init; }
}

// list representing the table
var table = new List<Record>();
```

**Comment by fasteddys** [comment]
thanks @6bee I understand that, I am trying to Auto Generate a POCO class from excel file which has the list of Class property names and types in two cols
for e.g..

```
Excel Col - ClassName 
Excel Col - AtrributeName
Excel Col - Type
```

![image](https://user-images.githubusercontent.com/96149622/159134791-ee60b2e2-5362-40fa-84ba-5a2f95369a95.png)

**Comment by 6bee** [comment]
If by "auto generate" you mean to emit these types at runtime, you could create instances of `Aqua.TypeSystem.TypeInfo` and use `Aqua.TypeSystem.Emit.TypeEmitter` to emit as .net types at runtime.

**Comment by fasteddys** [comment]
Not run time, compile time if fine, so we can maintain the meta data easily
