### ISSUE TITLE
Optimise dependencies for net 6

### ISSUE THREAD

**Issue by thompson-tomo** [6bee/aqua-core#43]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework when targeting net 6. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by 6bee** [comment]
Hi 
Thanks for your input and the PR - it's much appreciated!
Please note that client's may still need to add a package reference to _System.Text.Json_ if they need a _Type_ added only later to the library like [JsonUnknownDerivedTypeHandling](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonunknownderivedtypehandling) or [JsonPolymorphismOptions](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.metadata.jsonpolymorphismoptions). However, it's true that the dependency is not required by the _Aqua.Text.Json_ package itself and therefore may be removed. 
I'll accept your PR and make the required changes for the solution to build again.

**Comment by thompson-tomo** [comment]
Thanks @6bee 😃
